### ISSUE TITLE
FR: retries in the agent

### ISSUE THREAD

**Issue by dhalperi** [buildkite-plugins/artifacts-buildkite-plugin#54]
Many of our builds save an artifacts in step 1 and then download it in steps 2..N. We've seen several flaky builds this week based on failure to download artifacts from step 1 on only one of the later steps. They are all 502 errors.

Copying from an email discussion with support@, would be great if this was retried more proactively (with sensible backoff and limits, of course - don't want to make an outage worse).

> It looks like the call on the agent (https://github.com/buildkite/agent/blob/30f8cc6526b88833d0411bcbba1527862c3a5207/agent/artifact_searcher.go#L34) that the plugin is using is not utilising the retry functionality that we already have in the agent so we are going to look at adding that in.

I figured it wouldn't hurt to record in an issue :).

**Comment by dhalperi** [comment]
Public build example: https://buildkite.com/batfish/pybatfish-pre-commit/builds/12154#89d3b8d4-2414-4e2b-a8d0-49803112b7c3

**Comment by pzeballos** [comment]
Hey @dhalperi! sorry for the long delay! 😅 This sounds like a good functionality to add! It's on our backlog, and you are most than welcome to submit a PR and we'll be happy to review it 🙂

**Comment by toote** [comment]
Reading through the agent's code, it would seem that [artifact uploading does have retries](https://github.com/buildkite/agent/blob/00f2048f77c0e2d6808d1f234b339150569b7279/agent/artifact_batch_creator.go#L74-L75). What's more there is a [reported issue in the agent to implement it](https://github.com/buildkite/agent/issues/608) but reading through the whole thing I found that [it is already implemented as well](https://github.com/buildkite/agent/blob/00f2048f77c0e2d6808d1f234b339150569b7279/agent/download.go#L58-L59).

That said, the error in the pipeline is not with the downloading itself, but with an intermediate step in which the agent searches for the artifact's URL and that request failing. That is an actual agent issue that has been fixed in [agent 3.21.0 (from May 2020)](https://github.com/buildkite/agent/releases/tag/v3.21.0) as you can see that the [PR to solve the matter has the exact same error](https://github.com/buildkite/agent/pull/1210).
